CI: check version file is up to date

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -16,10 +16,18 @@ jobs:
     - uses: actions/checkout@v2
     - name: install-deps
       run: sudo apt install libyaml-cpp-dev libatasmart-dev cmake
-    - name: build
+    - name: cmake
       run: |
         mkdir build
         cmake -B build
-        cmake --build build
+    - name: check version
+      run: |
+        if [[ -n $(git diff -- VERSION) ]]; then
+          echo "Error: VERSION file not in sync:"
+          git diff -- VERSION
+          exit 1
+        fi
+    - name: compile
+      run: cmake --build build
     - name: install
       run: sudo cmake --install ${{ github.workspace }}/build
